# Generated by Django 5.1.2 on 2024-11-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_presentes_reservado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acompanhante', models.CharField(max_length=100)),
                ('acompanhante_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='noivos.convidados')),
            ],
        ),
    ]
